### ISSUE TITLE
eggs crash on startup with crow connected

### ISSUE THREAD

**Issue by fbotello** [andr-ew/eggs#1]
consistently having the script freeze on running it with crow connected to norns. i guess its not frozen because if i click on a note it will send out the note about 30-50 seconds after pressed. it seems to work if i load the script first then connect the crow to the norns.

**Comment by andr-ew** [comment]
@fbotello if you have time would you mind trying to reproduce this on the [latest release](https://github.com/andr-ew/eggs/releases/tag/v0.3.0) ?

I haven't experienced this & thus have not attempted to fix it, but the new version is mostly a rewrite from v0.1 so it's possible that the issue may be gone

this may be related to starting up with crow input 1 being mapped to jf's shift, which was always on in v0.1, but now needs to be mapped using K1+E1 on the jf page. so to reproduce the issue you may need to do that mapping, then exit to save the PSET & reload.

**Comment by fbotello** [comment]
issue seems to be fixed! couldn't replicate it after updating.
